/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  community: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "link",
      href: "/changelog",
      label: "更新日志",
    },
    {
      type: "link",
      href: "/showcase",
      label: "展示",
    },
    {
      type: "link",
      href: "/feature-requests",
      label: "特性请求",
    },
    {
      type: "link",
      label: "在Discord上与我们聊天",
      href: "https://discord.gg/docusaurus",
    },
  ],
};
